### PR TITLE
Simplify Sagittarius build and add r7rs-script

### PR DESCRIPTION
**Pull request by lassik**
@weinholt What do you think about these changes?

### CODE REVIEW

**Comment by lassik** [comment]
The old Dockerfile had most of the build in one RUN step:

```
RUN set -uxe; \
    cmake . -DCMAKE_INSTALL_PREFIX=/usr/local/sagittarius; \
    make; \
    make install; \
    make clean
```

I like to break these down to individual RUNs since one of them often fails when changing the Dockerfile. Then the results of the preceding steps can come from cache instead of being re-run every time.

**Comment by weinholt** [comment]
Looks good, but I'd rather keep the SHA256 comparison. I like to know what I base my builds on.

**Comment by lassik** [comment]
OK, I'll put it back.

Isn't there a cleaner-looking way to write the checksum comparisons than a miniature shell script? What if we store the correct checksum file in the repo and COPY it to the build container?

**Comment by weinholt** [comment]
It would be neater if Dockerfile had a built-in checksum command. :) But I like that the SHA256 is just next to the URL, since that makes it much harder to forgot to change it when you update the version number.

**Comment by lassik** [comment]
> It would be neater if Dockerfile had a built-in checksum command. :)

It would indeed :) But that wouldn't work for things that need to be FTP'd or git cloned.

> But I like that the SHA256 is just next to the URL, since that makes it much harder to forgot to change it when you update the version number.

I see your point. However, if we have a `sha256 -c` command in the file (as we should) the build is stopped dead in its tracks if you forget to update the hash. So we won't get invalid builds.

**Comment by lassik** [comment]
As an experiment, I put a `checksum` file in the s7 branch: https://github.com/weinholt/scheme-docker/tree/s7/s7. The Docker file uses COPY to copy it into the /build directory inside the container and then just `sha256sum -c checksum`. I think it looks quite neat now.

**Comment by weinholt** [comment]
Ok, the way it's done in the s7 branch looks good.

**Comment by lassik** [comment]
Checksum done. Pushed my changes to the branch, ready to build a container.

**Pull request merged**
